# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
- group: overloadedfrida

steps:
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'overloadfrida.mobileprovision'
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'sharat_overloadfrida.p12'
    certPwd: $(certpass)
- task: Xcode@5
  inputs:
    actions: 'build'
    packageApp: true
    signingOption: 'manual'
    provisioningProfileUuid: '933fe240-ff57-4625-ac91-ec86c3ccfb0d'
    scheme: ''
    exportPath: 'output'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
    
- task: appknox@0
  inputs:
    filePath: 'output/overloadfrida.ipa'
    accessToken: '$(appknoxtoken)'
    riskThreshold: 'high'